### ISSUE TITLE
Blog content too wide

### ISSUE THREAD

**Issue by galenwinsor** [brown-ccv/ccv-website-nuxt#141]
# The issue

- The blog content currently doesn't have a `max-width` set, so the text at larger screens is wider than the [recommended](https://www.smashingmagazine.com/2014/09/balancing-line-length-font-size-responsive-web-design/) 45 to 85 characters.
- The blog content doesn't have any horizontal padding, so on narrower screens the text touches the edge of the screen.

# Proposed fix

Some addition to the `.content` class like this:

```css
.content {
  /* ... */
 display: grid;
 grid-template-columns: 1fr min(65ch, 100%) 1fr;
}

.content > * {
 grid-column: 2;
}
```

## Before

<img width="1159" alt="image" src="https://github.com/brown-ccv/ccv-website-nuxt/assets/57297033/6a196707-122e-421d-8de3-944f97bc5cca">

## After

<img width="1159" alt="image" src="https://github.com/brown-ccv/ccv-website-nuxt/assets/57297033/5ba548bc-33b8-4679-bb13-a07fe3b765b0">
