### ISSUE TITLE
Thursday, February 29 2024 doesn't exist for the Blog

### ISSUE THREAD

**Issue by hollandjg** [brown-ccv/ccv-website-nuxt#143]
With this front-matter:
```yaml

title: Project Portal Completed
...
date: 2024-02-29
```

the date gets rendered incorrectly:

<img width="521" alt="Screenshot 2024-02-02 at 16 51 28" src="https://github.com/brown-ccv/ccv-website-nuxt/assets/2803227/81e739a7-8c8c-4360-b278-3c503e5bb89d">
